version: '3.8'

networks:
  betinhooowNetwork:
    driver: bridge

services:
  app:
    image: carverify-app:latest
    container_name: carverify-app
    environment:
      - NODE_ENV='development'
      - URL_API='http://localhost:55802/api/'
    depends_on:
      - 'backend'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - betinhooowNetwork

  backend:
    image: carverify-api:latest
    build:
      context: ../carverify_backend/
      dockerfile: Dockerfile
    ports:
      - '55802:5000'
      - '44339:5001'
    container_name: carverify-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetcert
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetcert.pfx
    networks:
      - betinhooowNetwork
    volumes:
      - C:\.https\:/root/.aspnet/https
# RUN TO GENERATE CERTIFICATE IN "C:\.https\aspnetcert.pfx"
# dotnet dev-certs https -v -ep C:\.https\aspnetcert.pfx -p aspnetcert
# dotnet dev-certs https --trust
